EC23

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,25 +1,36 @@
-# .github/workflows/test.yml
-name: Test API
-# When it's trigger
+name: CI/CD to EC2
+
 on:
   push:
-    branches: main
-  pull_request:
-    branches: main
-# Tasks
+    branches:
+      - main
+
 jobs:
-  test:
+  deploy:
     runs-on: ubuntu-latest
+
     steps:
-    # To clone code to work on
-    - name: Checkout repository
-      uses: actions/checkout@v2
-    - name: Set up Node.js 18
-      uses: actions/setup-node@v2
+    - name: Checkout code
+      uses: actions/checkout@v3
+
+    - name: Set up SSH agent
+      uses: webfactory/ssh-agent@v0.5.3
       with:
-        node-version: 18.x
-    - name: Install dependencies
-      # Use Unix commands
-      run: npm install
-    - name: Run tests
-      run: npm test
+        ssh-private-key: ${{ secrets.EC2_KEY }}
+
+    - name: Run deployment script on EC2
+      env:
+        EC2_HOST: ${{ secrets.EC2_HOST }}
+        EC2_USER: ${{ secrets.EC2_USER }}
+        EC2_SSH_PORT: ${{ secrets.EC2_SSH_PORT }}
+      run: |
+        ssh -p $EC2_SSH_PORT -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'source ~/.bashrc' << 'EOF'
+          set -e # Exit immediately if a command exits with a non-zero status
+          echo "Pulling latest changes from git repository"
+          cd devops-ex
+          git pull
+          echo "Installing dependencies"
+          npm install
+          echo "Building the application"
+          pm2 restart all
+        EOF
